apiVersion: v1
kind: List
items:
- kind: Pod
  apiVersion: v1
  metadata:
    name: example-kubetron-pod1
    annotations:
      kubetron.network.kubevirt.io/networks: red, blue, green
  spec:
    containers:
      - name: example-container
        image: alpine
        command: ["sleep", "9999"]
    restartPolicy: Never
    nodeSelector:
      "kubernetes.io/hostname": "k8s-02"
- kind: Pod
  apiVersion: v1
  metadata:
    name: example-kubetron-pod2
    annotations:
      kubetron.network.kubevirt.io/networks: red, blue, green
  spec:
    containers:
      - name: example-container
        image: alpine
        command: ["sleep", "9999"]
    restartPolicy: Never
    nodeSelector:
      "kubernetes.io/hostname": "k8s-03"